# Configuración para Lengua Castellana y Literatura (011) - Baremo 2025
especialidad:
  codigo: "011"
  nombre: "Lengua Castellana y Literatura"
  nivel: "Profesores de Enseñanza Secundaria"
  
# Configuración del PDF
pdf:
  archivo: "data/rh03_257_2025_590_12_baremo_prov.pdf"
  pagina_inicio: 2
  pagina_fin: 10
  total_paginas: 9
  
# Validación de páginas clave
validacion:
  pagina_inicial:
    numero: 5
    puntuaciones_esperadas: [9.5700, 5.0000, 5.0000, 5.0000, 0.0000, 3.5000, 8.5000]
  pagina_final:
    numero: 10
    puntuaciones_esperadas: [4.5000, 1.5000, 1.5000, 1.0000, 0.5000]

# Patrones de extracción
extraccion:
  patron_puntuacion: r'\b\d+[.,]\d{4}\b'
  columnas_buscar: ["Total"]
  min_puntuacion: 0.0
  max_puntuacion: 10.0

# Configuración de visualización
visualizacion:
  titulo: "Distribución de Puntuaciones - Lengua Castellana y Literatura (011)"
  color_principal: "#2E8B57"  # Verde bosque
  bins: 50
  rango_puntuacion: [0, 10]
  
# Metadatos
metadatos:
  fuente: "Baremo Provisional CM 2025"
  url: "https://www.comunidad.madrid/sites/default/files/doc/educacion/rh03/rh03_257_2025_590_12_baremo_prov.pdf"
  fecha_extraccion: "2025-01-04"
  autor: "@joanh"
