# Configuración para Lengua Castellana y Literatura (004) - Baremo 2025
especialidad:
  codigo: "004"
  nombre: "Lengua Castellana y Literatura"
  nivel: "Profesores de Enseñanza Secundaria"
  
# Configuración del PDF
pdf:
  archivo: "data/rh03_257_2025_590_12_baremo_prov.pdf"
  pagina_inicio: 113
  pagina_fin: 359
  total_paginas: 247
  
# Validación de páginas clave
validacion:
  pagina_inicial:
    numero: 113
    puntuaciones_esperadas: [3.5000, 8.5000, 2.5000, 6.4084, 5.0000, 3.0000, 0.4792]
  pagina_final:
    numero: 359
    puntuaciones_esperadas: [8.0000, 7.3333, 0.1000, 4.5000, 3.0000]

# Patrones de extracción
extraccion:
  patron_puntuacion: r'\b\d+[.,]\d{4}\b'
  columnas_buscar: ["Total"]
  min_puntuacion: 0.0
  max_puntuacion: 10.0

# Configuración de visualización
visualizacion:
  titulo: "Distribución de Puntuaciones - Lengua Castellana y Literatura (004)"
  color_principal: "#2E8B57"  # Verde bosque
  bins: 50
  rango_puntuacion: [0, 10]
  
# Metadatos
metadatos:
  fuente: "Baremo Provisional CM 2025"
  url: "https://www.comunidad.madrid/sites/default/files/doc/educacion/rh03/rh03_257_2025_590_12_baremo_prov.pdf"
  fecha_extraccion: "2025-01-04"
  autor: "@joanh"
