especialidades:
  FILOSOFIA:
    codigo: "001"
    nombre: "FILOSOFIA"
    pagina_inicio: 2
    pagina_fin: 82
    candidatos_por_pagina: 7
    descripcion: "Profesores de Enseñanza Secundaria - Filosofía"
    total_candidatos: 561  # 80 páginas × 7 + 1 candidato final
  
  INFORMATICA:
    codigo: "107"
    nombre: "INFORMATICA" 
    pagina_inicio: 2649
    pagina_fin: 2697
    candidatos_por_pagina: 7
    descripcion: "Profesores de Enseñanza Secundaria - Informática"
    total_candidatos: 343
  
  MATEMATICAS:
    codigo: "008"
    nombre: "MATEMATICAS"
    pagina_inicio: null  # Configurar según PDF
    pagina_fin: null     # Configurar según PDF
    candidatos_por_pagina: 7
    descripcion: "Profesores de Enseñanza Secundaria - Matemáticas"
  
  FISICA_QUIMICA:
    codigo: "010" 
    nombre: "FISICA_QUIMICA"
    pagina_inicio: null  # Configurar según PDF
    pagina_fin: null     # Configurar según PDF
    candidatos_por_pagina: 7
    descripcion: "Profesores de Enseñanza Secundaria - Física y Química"
  
  INGLES:
    codigo: "011"
    nombre: "INGLES"
    pagina_inicio: 1395
    pagina_fin: 1678
    candidatos_por_pagina: 7
    descripcion: "Profesores de Enseñanza Secundaria - Inglés"
    total_candidatos: 1984  # 283 páginas × 7 + 3 candidatos final

# Configuración general
configuracion:
  patron_dni: "^\*\*\*\*.*\*"
  patron_numeros: "\b(\d{1,2},\d{4})\b"
  rango_puntuaciones: [0.0, 10.0]
  pdf_original: "rh03_257_2025_590_12_baremo_prov.pdf"
