especialidades:
  FILOSOFIA:
    codigo: "001"
    nombre: "FILOSOFIA"
    pagina_inicio: 2
    pagina_fin: 82
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - Filosof칤a"
    total_candidatos: 561  # 80 p치ginas 칑 7 + 1 candidato final
  
  INFORMATICA:
    codigo: "107"
    nombre: "INFORMATICA" 
    pagina_inicio: 2649
    pagina_fin: 2697
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - Inform치tica"
    total_candidatos: 343
  
  MATEMATICAS:
    codigo: "006"
    nombre: "MATEMATICAS"
    pagina_inicio: null  # Configurar seg칰n PDF
    pagina_fin: null     # Configurar seg칰n PDF
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - Matem치ticas"
  
  FISICA_QUIMICA:
    codigo: "007" 
    nombre: "FISICA_QUIMICA"
    pagina_inicio: null  # Configurar seg칰n PDF
    pagina_fin: null     # Configurar seg칰n PDF
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - F칤sica y Qu칤mica"
  
  FRANCES:
    codigo: "010"
    nombre: "FRANCES"
    pagina_inicio: 1356
    pagina_fin: 1394
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - Franc칠s"
    total_candidatos: 273  # 39 p치ginas 칑 7
  
  INGLES:
    codigo: "011"
    nombre: "INGLES"
    pagina_inicio: 1395
    pagina_fin: 1678
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - Ingl칠s"
    total_candidatos: 1984  # 283 p치ginas 칑 7 + 3 candidatos final

  TECNOLOGIA:
    codigo: "019"
    nombre: "TECNOLOGIA"
    pagina_inicio: 2269
    pagina_fin: 2377
    candidatos_por_pagina: 7
    descripcion: "Profesores de Ense침anza Secundaria - Tecnolog칤a"
    total_candidatos: 763
    icono: "游댢"
    validacion_inicial: [2.5000, 5.1667, 1.2500, 8.0000, 3.5000, 1.5500, 3.8000, 0.5000, 6.4167, 6.0533, 9.7500, 0.8500, 4.5000, 5.0000, 0.5667, 9.0000, 0.0000, 0.0000, 8.0000, 5.7000, 3.9584]
    validacion_final: [9.0000, 4.1667, 7.5000, 8.8333, 6.5000, 4.5500, 1.2625, 3.5000, 3.0833, 8.0000, 8.0000, 1.4167, 6.2500, 8.7000, 6.1250, 5.0000, 0.0000, 2.1000, 7.4167, 4.0833, 2.9500]

# Configuraci칩n general
configuracion:
  patron_dni: "^\*\*\*\*.*\*"
  patron_numeros: "\b(\d{1,2},\d{4})\b"
  rango_puntuaciones: [0.0, 10.0]
  pdf_original: "rh03_257_2025_590_12_baremo_prov.pdf"
