# Configuración para Filosofía (001) - Baremo 2025
especialidad:
  codigo: "001"
  nombre: "Filosofía"
  nivel: "Profesores de Enseñanza Secundaria"
  
# Configuración del PDF
pdf:
  archivo: "data/rh03_257_2025_590_12_baremo_prov.pdf"
  pagina_inicio: 1
  pagina_fin: 112
  total_paginas: 112
  
# Validación de páginas clave
validacion:
  pagina_inicial:
    numero: 1
    puntuaciones_esperadas: [5.0000, 3.5000, 8.5000, 2.5000, 6.4084]
  pagina_final:
    numero: 112
    puntuaciones_esperadas: [8.0000, 7.3333, 0.1000, 4.5000, 3.0000]

# Patrones de extracción
extraccion:
  patron_puntuacion: r'\b\d+[.,]\d{4}\b'
  columnas_buscar: ["Total"]
  min_puntuacion: 0.0
  max_puntuacion: 10.0

# Configuración de salida
output:
  csv: "puntuaciones_filosofia_001.csv"
  txt: "puntuaciones_filosofia_001.txt"
  lista: "lista_filosofia_001.py"
  estadisticas: "estadisticas_filosofia_001.txt"
  grafico: "baremo_filosofia_001_2025.png"

# Metadatos
metadata:
  año: 2025
  convocatoria: "Provisional"
  fuente: "Comunidad de Madrid"
  fecha_publicacion: "2025-07-01"
  autor_extraccion: "@joanh"
  asistente: "Claude Sonnet 4.0"
